version: "3.1"
services:
  redis:
    image: nvcr.io/nvidia/pytorch:24.04-py3
    container_name: gpu_env
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /mnt/nfs/zsd_server:/mnt/nfs/zsd_server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    ulimits:
      stack: 67108864
      memlock:
        soft: -1
        hard: -1
    stdin_open: true
    tty: true
    network_mode: "host"
    logging:
      options:
        max-size: "10m"